development: &default
  adapter: postgresql
  database: Torflix_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['TORFLIX_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['TORFLIX_DB_1_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: Torflix_test

production:
  <<: *default
  database: Torflix_production
