# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dad2c41603c9fbb4b87718d3d023e49df2e67faf650e698758af36d568f97787053aa65ada186f9a4ec71d2fd073fb63ee57168803343a9bce09fd691c9ceaae

test:
  secret_key_base: 1f0b67ad71619c79ada146c29abdaa498255fbc84f4091147345298602a4cd76f2fed068d4041d364f5fb108ddadc7140698c38fddd06fae685c5db57c17c2c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
